In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 
import sklearn.metrics as mt
import seaborn as sns
import warnings

from sklearn.ensemble import RandomForestClassifier
warnings.filterwarnings('ignore')

In [4]:
weather_df = pd.read_csv('./data/pre_labeled_weather.csv',index_col = 0)

In [5]:
weather_df = pd.read_csv('./data/MiceImputed_weather.csv',index_col = 0)

In [6]:
weather_df

location    Date  MinTemp  MaxTemp  Rainfall  WindGustSpeed  \
0           45.0     0.0     12.6     23.2       0.5            6.4   
1           45.0     1.0     10.6     24.1       0.0            6.5   
2           45.0     2.0     14.2     25.1       0.0            7.0   
3           45.0     3.0     12.1     21.1       0.0            6.1   
4           45.0     4.0     11.9     15.4       0.0            6.5   
...          ...     ...      ...      ...       ...            ...   
343701      17.0  3647.0      9.8     20.3       0.0            4.8   
343702      17.0  3648.0      7.9     21.5       0.0            5.4   
343703      17.0  3649.0      8.3     19.9       0.0            3.6   
343704      17.0  3650.0      8.2     22.7       0.0            4.1   
343705      17.0  3651.0      9.5     23.7       0.0            3.9   

        WindGustDir   Sunshine  Evaporation  TodayRain  ...  Cloud9am  \
0               7.0  17.627755     4.696022        0.0  ...       0.0   
1              15.0  21.060788     6.238979        0.0  ...       3.0   
2               7.0  24.272884     6.987526        0.0  ...       0.0   
3               7.0  14.398951     3.787547        0.0  ...       9.0   
4               7.0   7.348844     1.284132        0.0  ...       8.0   
...             ...        ...          ...        ...  ...       ...   
343701         14.0  19.648829     5.552254        0.0  ...       4.0   
343702         14.0  18.247347     5.144071        0.0  ...       0.0   
343703         11.0  20.493692     5.126407        0.0  ...       2.0   
343704         11.0  22.913542     5.828915        0.0  ...       0.0   
343705         11.0  23.069935     5.727928        0.0  ...       0.0   

        Humidity9am  WindSpeed9am  Temp9am  Pressure3pm  WindDir3pm  Cloud3pm  \
0              66.0           1.6     18.3        998.7         9.0       6.0   
1              30.0           5.1     18.6       1000.8         0.0       2.0   
2              26.0           3.1     22.2       1002.8         0.0       0.0   
3              66.0           0.8     17.0       1005.5         2.0       3.0   
4              90.0           3.8     14.7       1013.2         6.0       9.0   
...             ...           ...      ...          ...         ...       ...   
343701         48.0           1.2     14.4       1006.8         8.0       1.0   
343702         50.0           1.7     15.9       1006.5        15.0       7.0   
343703         66.0           1.2     13.0       1014.3         8.0       0.0   
343704         59.0           1.0     15.5       1014.0        11.0       0.0   
343705         70.0           1.2     17.3       1013.6        12.0       0.0   

        Humidity3pm  WindSpeed3pm  Temp3pm  
0              51.0           4.2     19.3  
1              35.0           2.7     20.5  
2              31.0           2.1     22.9  
3              70.0           2.8     18.3  
4              89.0           4.6     13.9  
...             ...           ...      ...  
343701         35.0           2.4     19.5  
343702         42.0           2.2     20.6  
343703         37.0           2.7     18.9  
343704         39.0           2.6     21.3  
343705         44.0           2.6     22.6  

[343706 rows x 23 columns]

In [7]:
# 'n_estimators':[100,200, 300, 400],
#     'max_depth' : [6, 8, 10, 12, 16, 20], 
#     'min_samples_leaf' : [8, 12, 18 ],
#     'min_samples_split' : [8, 16, 20]

In [8]:
Y = weather_df['TomorrowRain']
weather_df.drop(['TomorrowRain'], axis = 1, inplace = True)
X = weather_df

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
                                                    test_size=0.2 , random_state= 156, stratify=Y)

In [15]:
import sklearn.metrics as mt
def get_clf_eval(y_test, pred=None):
    confusion = mt.confusion_matrix( y_test, pred)
    accuracy = mt.accuracy_score(y_test , pred)
    precision = mt.precision_score(y_test , pred)
    recall = mt.recall_score(y_test , pred)
    f1 = mt.f1_score(y_test,pred)

    print('오차 행렬:')
    print(confusion)
    
    print('\n정확도: {0:.4f} \n정밀도: {1:.4f} \n재현율: {2:.4f} \n    F1: {3:.4f}'.format(accuracy, precision, recall, f1))

In [16]:
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train , y_train)
pred = rf_clf.predict(X_test)
get_clf_eval(y_test, pred)

오차 행렬:
[[53426  1276]
 [ 9487  4553]]

정확도: 0.8434 
정밀도: 0.7811 
재현율: 0.3243 
    F1: 0.4583


In [17]:
rf_clf = RandomForestClassifier(random_state=0, max_depth = 10)
rf_clf.fit(X_train , y_train)
pred = rf_clf.predict(X_test)
get_clf_eval(y_test, pred)

오차 행렬:
[[53559  1143]
 [11183  2857]]

정확도: 0.8207 
정밀도: 0.7143 
재현율: 0.2035 
    F1: 0.3167


In [19]:
rf_clf = RandomForestClassifier(random_state=10, max_depth = 20)
rf_clf.fit(X_train , y_train)
pred = rf_clf.predict(bX_test)
get_clf_eval(y_test, pred)

오차 행렬:
[[53388  1314]
 [ 9735  4305]]

정확도: 0.8393 
정밀도: 0.7662 
재현율: 0.3066 
    F1: 0.4380


In [21]:
rf_clf = RandomForestClassifier(random_state=10, max_depth = 20,n_estimators=50)
rf_clf.fit(X_train , y_train)
pred = rf_clf.predict(X_test)
get_clf_eval(y_test, pred)

오차 행렬:
[[53314  1388]
 [ 9738  4302]]

정확도: 0.8381 
정밀도: 0.7561 
재현율: 0.3064 
    F1: 0.4361


In [22]:
rf_clf = RandomForestClassifier(random_state=10, max_depth = 20,n_estimators=200)
rf_clf.fit(X_train , y_train)
pred = rf_clf.predict(X_test)
get_clf_eval(y_test, pred)

오차 행렬:
[[53464  1238]
 [ 9735  4305]]

정확도: 0.8404 
정밀도: 0.7767 
재현율: 0.3066 
    F1: 0.4397


In [23]:
rf_clf = RandomForestClassifier(random_state=10, max_depth = 20,n_estimators=400)
rf_clf.fit(X_train , y_train)
pred = rf_clf.predict(X_test)
get_clf_eval(y_test, pred)

오차 행렬:
[[53466  1236]
 [ 9739  4301]]

정확도: 0.8403 
정밀도: 0.7768 
재현율: 0.3063 
    F1: 0.4394


In [26]:
rf_clf = RandomForestClassifier(random_state=10, max_depth = 20,n_estimators=200,criterion="entropy")
rf_clf.fit(X_train , y_train)
pred = rf_clf.predict(X_test)
get_clf_eval(y_test, pred)

오차 행렬:
[[53460  1242]
 [ 9745  4295]]

정확도: 0.8402 
정밀도: 0.7757 
재현율: 0.3059 
    F1: 0.4388


In [27]:
rf_clf = RandomForestClassifier(random_state=10, max_depth = 20,n_estimators=200,criterion="log_loss")
rf_clf.fit(X_train , y_train)
pred = rf_clf.predict(X_test)
get_clf_eval(y_test, pred)

오차 행렬:
[[53460  1242]
 [ 9745  4295]]

정확도: 0.8402 
정밀도: 0.7757 
재현율: 0.3059 
    F1: 0.4388
